server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.58.101
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ly:
  page:
    destPath: C:/lesson/heima37/nginx-1.12.2/html/item
