server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.58.101
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ly:
  jwt:
    pubKeyPath: C:/lesson/heima37/rsa/id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称